# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.drop_shadow_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.drop_shadow_layout.setContentsMargins(10, 10, 10, 10)
        self.drop_shadow_layout.setSpacing(0)
        self.drop_shadow_layout.setObjectName("drop_shadow_layout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0284091, y1:0.045, x2:0.960227, y2:0.972, stop:0 rgba(75, 108, 183, 255), stop:0.806818 rgba(24, 40, 72, 255));\n"
"border-radius:10px\n"
"")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar.setStyleSheet("background-color:none")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_buttons = QtWidgets.QFrame(self.title_bar)
        self.frame_buttons.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons.setObjectName("frame_buttons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_buttons)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_minimise = QtWidgets.QPushButton(self.frame_buttons)
        self.bt_minimise.setMaximumSize(QtCore.QSize(17, 17))
        self.bt_minimise.setToolTipDuration(-1)
        self.bt_minimise.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    \n"
"    background-color: rgb(85, 255, 127);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 255, 127,150);\n"
"    \n"
"}\n"
"")
        self.bt_minimise.setText("")
        self.bt_minimise.setObjectName("bt_minimise")
        self.horizontalLayout_2.addWidget(self.bt_minimise)
        self.bt_maximise = QtWidgets.QPushButton(self.frame_buttons)
        self.bt_maximise.setMaximumSize(QtCore.QSize(17, 17))
        self.bt_maximise.setToolTipDuration(-1)
        self.bt_maximise.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    \n"
"    background-color: rgb(255, 170, 0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 170, 0 ,150);\n"
"    \n"
"}")
        self.bt_maximise.setText("")
        self.bt_maximise.setObjectName("bt_maximise")
        self.horizontalLayout_2.addWidget(self.bt_maximise)
        self.bt_close = QtWidgets.QPushButton(self.frame_buttons)
        self.bt_close.setMaximumSize(QtCore.QSize(17, 17))
        self.bt_close.setToolTipDuration(-1)
        self.bt_close.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 0, 0,150);\n"
"    \n"
"}")
        self.bt_close.setText("")
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout_2.addWidget(self.bt_close)
        self.horizontalLayout.addWidget(self.frame_buttons)
        self.verticalLayout.addWidget(self.title_bar)
        self.content_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.content_bar.setStyleSheet("background-color:none")
        self.content_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bar.setObjectName("content_bar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.content_bar)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content_bar)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(72)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.profile_chooser = QtWidgets.QWidget()
        self.profile_chooser.setObjectName("profile_chooser")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.profile_chooser)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.profile_main = QtWidgets.QFrame(self.profile_chooser)
        self.profile_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.profile_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profile_main.setObjectName("profile_main")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.profile_main)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.left_panel = QtWidgets.QFrame(self.profile_main)
        self.left_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_panel.setObjectName("left_panel")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.left_panel)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.prev_arrow = QtWidgets.QPushButton(self.left_panel)
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(120)
        self.prev_arrow.setFont(font)
        self.prev_arrow.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(242, 243, 244);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    color: rgb(242, 243, 244,150);\n"
"    \n"
"}")
        self.prev_arrow.setObjectName("prev_arrow")
        self.verticalLayout_11.addWidget(self.prev_arrow)
        self.horizontalLayout_5.addWidget(self.left_panel)
        self.the_main_profile = QtWidgets.QFrame(self.profile_main)
        self.the_main_profile.setStyleSheet("")
        self.the_main_profile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.the_main_profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.the_main_profile.setObjectName("the_main_profile")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.the_main_profile)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.text_frame = QtWidgets.QFrame(self.the_main_profile)
        self.text_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_frame.setObjectName("text_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.text_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.profile_text = QtWidgets.QLabel(self.text_frame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(22)
        self.profile_text.setFont(font)
        self.profile_text.setStyleSheet("color: rgb(255, 255, 255);")
        self.profile_text.setText("")
        self.profile_text.setObjectName("profile_text")
        self.horizontalLayout_6.addWidget(self.profile_text, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.text_frame)
        self.circle_frame = QtWidgets.QFrame(self.the_main_profile)
        self.circle_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circle_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circle_frame.setObjectName("circle_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.circle_frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.circle_button = QtWidgets.QPushButton(self.circle_frame)
        self.circle_button.setMinimumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(72)
        self.circle_button.setFont(font)
        self.circle_button.setStyleSheet("QPushButton{\n"
"    background-color:none;\n"
"    border:5px solid  rgb(242, 243, 244);\n"
"    border-radius:125px;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:5px solid  rgb(242, 243, 244,150);\n"
"\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(248, 255, 0, 255), stop:0.702381 rgba(58, 213, 159, 255));\n"
"\n"
"}\n"
"\n"
"")
        self.circle_button.setText("")
        self.circle_button.setObjectName("circle_button")
        self.verticalLayout_6.addWidget(self.circle_button)
        self.verticalLayout_5.addWidget(self.circle_frame)
        self.placeholder1 = QtWidgets.QFrame(self.the_main_profile)
        self.placeholder1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.placeholder1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.placeholder1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.placeholder1.setObjectName("placeholder1")
        self.verticalLayout_5.addWidget(self.placeholder1)
        self.horizontalLayout_5.addWidget(self.the_main_profile)
        self.right_panel = QtWidgets.QFrame(self.profile_main)
        self.right_panel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_panel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.right_panel.setLineWidth(0)
        self.right_panel.setObjectName("right_panel")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.right_panel)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.placeholder2 = QtWidgets.QFrame(self.right_panel)
        self.placeholder2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.placeholder2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.placeholder2.setObjectName("placeholder2")
        self.verticalLayout_7.addWidget(self.placeholder2)
        self.next_arrow = QtWidgets.QPushButton(self.right_panel)
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(120)
        self.next_arrow.setFont(font)
        self.next_arrow.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(242, 243, 244);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    color: rgb(242, 243, 244,150);\n"
"    \n"
"}")
        self.next_arrow.setObjectName("next_arrow")
        self.verticalLayout_7.addWidget(self.next_arrow)
        self.placeholder3 = QtWidgets.QFrame(self.right_panel)
        self.placeholder3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.placeholder3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.placeholder3.setObjectName("placeholder3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.placeholder3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.new_button_frame = QtWidgets.QFrame(self.placeholder3)
        self.new_button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_button_frame.setObjectName("new_button_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.new_button_frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.New_button = QtWidgets.QPushButton(self.new_button_frame)
        self.New_button.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(30)
        self.New_button.setFont(font)
        self.New_button.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius:20px;\n"
"    background-color: rgba(242, 243, 244,255);\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(242, 243, 244,150);\n"
"\n"
"}")
        self.New_button.setObjectName("New_button")
        self.verticalLayout_8.addWidget(self.New_button)
        self.horizontalLayout_7.addWidget(self.new_button_frame)
        self.placeholder4 = QtWidgets.QFrame(self.placeholder3)
        self.placeholder4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.placeholder4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.placeholder4.setObjectName("placeholder4")
        self.horizontalLayout_7.addWidget(self.placeholder4)
        self.verticalLayout_7.addWidget(self.placeholder3)
        self.horizontalLayout_5.addWidget(self.right_panel)
        self.verticalLayout_4.addWidget(self.profile_main)
        self.profile_app_drawer = QtWidgets.QFrame(self.profile_chooser)
        self.profile_app_drawer.setMaximumSize(QtCore.QSize(16777215, 50))
        self.profile_app_drawer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.profile_app_drawer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profile_app_drawer.setObjectName("profile_app_drawer")
        self.app_drawer_layout = QtWidgets.QHBoxLayout(self.profile_app_drawer)
        self.app_drawer_layout.setContentsMargins(400, -1, 400, -1)
        self.app_drawer_layout.setObjectName("app_drawer_layout")
        self.verticalLayout_4.addWidget(self.profile_app_drawer)
        self.stackedWidget.addWidget(self.profile_chooser)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Profile_name_Field = QtWidgets.QLineEdit(self.page_2)
        self.Profile_name_Field.setGeometry(QtCore.QRect(40, 30, 521, 131))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(72)
        self.Profile_name_Field.setFont(font)
        self.Profile_name_Field.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color:rgb(255, 255, 255);")
        self.Profile_name_Field.setText("")
        self.Profile_name_Field.setObjectName("Profile_name_Field")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(40, 170, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.content_bar)
        self.credits_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.credits_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.credits_bar.setStyleSheet("background-color:none")
        self.credits_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_bar.setObjectName("credits_bar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.credits_bar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_credit_label = QtWidgets.QFrame(self.credits_bar)
        self.frame_credit_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_credit_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_credit_label.setObjectName("frame_credit_label")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_credit_label)
        self.horizontalLayout_4.setContentsMargins(15, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_credits = QtWidgets.QLabel(self.frame_credit_label)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(8)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_4.addWidget(self.label_credits)
        self.horizontalLayout_3.addWidget(self.frame_credit_label)
        self.frame_grip = QtWidgets.QFrame(self.credits_bar)
        self.frame_grip.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_grip.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_3.addWidget(self.frame_grip)
        self.verticalLayout.addWidget(self.credits_bar)
        self.drop_shadow_layout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Budget Planner"))
        self.bt_minimise.setToolTip(_translate("MainWindow", "Minimise"))
        self.bt_maximise.setToolTip(_translate("MainWindow", "Maximise"))
        self.bt_close.setToolTip(_translate("MainWindow", "Close"))
        self.prev_arrow.setText(_translate("MainWindow", "<"))
        self.next_arrow.setText(_translate("MainWindow", ">"))
        self.New_button.setText(_translate("MainWindow", "+"))
        self.label.setText(_translate("MainWindow", "Please enter your profile name"))
        self.label_credits.setText(_translate("MainWindow", "Made by Arjun , Govind and Rishi "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
